spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop; # MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # drop-create on application start
    properties:
      hibernates:
        show_sql: true # system out (should not on production)
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug # by logger
